Replace cuba test with RSpec request spec. (#4)
* Replace cuba test with RSpec request spec.

* Replace personal email address with generic one.

* Fix rubocop linter issues, add personal dir to Exclude list.

* Change http status code from 201 to :created for semaphore.

* Use Rails encrypted secrets, Enable Basic Auth, Refactor RSpec Requests.

Use Rails.env = 'test' (rather than 'staging') to match semaphore
environment.

Refactor RSpec Requests to properly return status codes.

Reference Rails.application.credentials.basic_auth[:admin_name]
rather han ENV.fetch('ADMIN_NAME').

Create Semaphore secret file, uhura_rails_secret.yml, to store
RAILS_MASTER_KEY.

* Fix Semaphore db config load error.

ERROR:
bundle exec rake rubocop
/home/semaphore/uhura/vendor/bundle/ruby/2.6.0/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:251: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
rake aborted!
NoMethodError: Cannot load database configuration:
undefined method `[]' for nil:NilClass

* Fix Semaphore error.

ERROR:
NameError: Cannot load database configuration:
undefined local variable or method `postgres' for main:Object

* Copy config/credentials/test.key to RAILS_MASTER_KEY for semaphore.

* Try again.

* Fix postgres username value in database.yml.

* Add RAILS_MASTER_KEY to Semaphore Lint step.

Also, update test and production Rails credentials.

* Pasted actual key value to RAILS_MASTER_KEY in sempaphore.yml

* Add Semaphore env vars for database.yml.

See https://semaphoreci.com/docs/available-environment-variables.html#variables-in-ruby-projects-with-databases

* Use given Sempaphore database username and password values

* Add postgresql DATABASE_URL to semaphore.yml

See https://docs.semaphoreci.com/article/73-ruby#4-1-using-database_url`

* Remove Semaphore v1 env vars from semaphore.yml

* Replace text with ENV.fetch('RAILS_MASTER_KEY') in semaphore.yml.

* Try again.

* Try again.

* Use RAILS_MASTER_KEY env var set by uhura_rails_secret.yml

* Update semaphore secret file: uhura

[lex@k2 uhura]$ sem delete secret uhura
Secret 'uhura' deleted.
[lex@k2 uhura]$ sem create -f config/credentials/uhura_rails_secret.yml

* Remove RAILS_MASTER_KEY env var from semaphore Lint task

* Change name of semaphore secrets file and try again...

* Fix typos in semaphore.yml

* Fix typo. Try again.

* Move echo command. Try again.

* Try different syntax. Try again.

* Add DATABASE_URL to Lint step

* Add RAILS_MASTER_KEY back to semaphore.yml

* Change syntax in sem_uhura_secrets.yml

* Remove secrets file

* Try secrets file

* Minor change to test secrets on semaphore

* Another minor change to test sem secrets

* Use environment variable in sempaphore.yml.

* Refactor return_error and return_success.

Also, correct typo in PGUSER env var value for test environment.

* Rubocop fixes.

* Remove jbuilder files from view.

Refactor a test description.